### PR TITLE
Added CSS for the novote icon

### PR DESCRIPTION
**Pull request by joefarebrother**
I have only put 3 names in the t16 list, for testing, as I don't have the full list.

### CODE REVIEW

**Comment by lachlanhunt** [comment]
I have obtained a complete list of users from ccfiande. See members.json that I pushed today. Each user has a corresponding vote, which I plan to use to display the correct icon, at least for the NOVOTE users. They are the ones that were dropped.

I'm not sure how we should deal with the STAY votes. They are the ones who chose to stay in ccfiande. I don't have a corresponding list of votes for sokuku, and those STAY votes don't necessarily correspond with how they may have voted in cckufi.

I also think we should change the way the flair is implemented, much more like how Karmancer does it for the button flairs. All of the real icons are available, so we don't need to emulate them with CSS.

**Comment by lachlanhunt** [comment]
Just to clarify, members.json is the complete list (6712 users) of cckufi members and the dropped users from ccfiande.

**Comment by joefarebrother** [comment]
My view was that the grow flair would indicate who made it to ccKufi (as the managed to grow into t17, regardless of whether they voted to or not), and that the novote flair indicates who was dropped during the final merge between ccfiand and sokuku. So the stay votes won't be something to worry about.

I have a feeling that rendering an image may be slightly less efficient than rendering pure CSS, but I don't really know whether this would add up into something significant for large threads. In my own fork I'm probably going to keep using CSS emulated icons for this reason.

**Comment by joefarebrother** [comment]
I have now done some processing on your csv files to extract the complete list of users kicked from ccfiande.

I don't think we need an equivalent list for sokuku as afkers were already being purged and most people had already voted grow (or stay), unlike in ccfiande where votes weren't being processed.

I'm still a github noob, so is that automatically included in this PR or do I need to file a new one?

**Comment by lachlanhunt** [comment]
The [sprites](https://b.thumbs.redditmedia.com/HduvVOZ7DU4siuK5yz5EFnRhEjBtEnEutE6K8phbumU.png). They're small and already loaded for anyone who visits the ccKufi subreddit, so l'm not concerned about loading time. We could alternatively include them in the script as a data: URL, so they add no additional loading time at all.

This PR has merge conflicts. Also, we're only up to version 0.0.3.  Can you resolve the conflicts by merging my master back into yours, and can you close and resubmit this PR for merging into my dev branch instead? That way, it won't be immediately published for everyone as soon as I click merge.

If you need help merging my changes back into yours, follow these instructions, in this order:
1. https://help.github.com/articles/configuring-a-remote-for-a-fork/
2. https://help.github.com/articles/syncing-a-fork/

**Comment by lachlanhunt** [comment]
Just to clarify, you don't need to put the sprites in before re-submitting your pull request. I'll do that myself later. Just resolve the conflicts.

**Comment by lachlanhunt** [comment]
I ended up implementing a more robust flair system using the sprites. It looks better with the real icons, rather than the hacky CSS alternatives. So I will now close this PR.

**Comment by joefarebrother** [comment]
Fair enough. 

As both of our forks are now functionally equivalent, just implemented in different ways, and I can't think of any additional features, I probably won't be sending any more PRs.

**Pull request closed without merging**
